#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

case "$1" in
    help | selinux:help)
        help_content_func() {
            declare desc="return help_content string"
            cat<<help_content
    selinux, Does nothing
help_content
        }

        if [[ $1 = "selinux:help" ]]; then
            echo -e 'Usage: none, this plugin does not have any commands!'
            echo 'Additional commands:'
            help_content_func | sort | column -c2 -t -s,
        else
            help_content_func
        fi
        ;;

    *)
        exit $DOKKU_NOT_IMPLEMENTED_EXIT
        ;;
esac

