#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"
format_restorecon_output () {
    { grep '^restorecon reset' || true; } | awk '{ print "           " $3 " : " $5 }'
}
clean_stderr () {
    { grep -v 'Full path required for exclude' || true; }
}

# Restore SELinux context for nginx config
echo '       Restoring SELinux context'
/usr/sbin/restorecon -v  "$DOKKU_ROOT/$APP/nginx.conf"   |& clean_stderr | format_restorecon_output
if [ -d "$DOKKU_ROOT/$APP/nginx.conf.d" ]; then
    /usr/sbin/restorecon -rv "$DOKKU_ROOT/$APP/nginx.conf.d" |& clean_stderr | format_restorecon_output
fi

